config/routes.rb
Rails.application.routes.draw do

  # GENERAL ROUTES
  root 'board_line#index'

  devise_for :users
  resources :users, only: [:show, :update] do
    member do
      patch 'update_avatar'
      put 'update_avatar'
      post 'like'
      delete 'unlike'
    end

    resources :profile, only: [:index]
    # 프로필 정보 수정 (닉네임, 한줄소개)
    put   '/profile' => 'profile#update'
    patch '/profile' => 'profile#update'
    # Social 정보 수정
    post  '/social'  => 'profile#social'
  end
  # S Finger login
  get '/sfinger' => 'users#sfinger'
  post '/sfinger' => 'users#sfinger_register'

  # 게시판 형태
  resources :boards, only: [] do
    resources :comments, only: [:create, :edit, :destroy, :update]
  end
  resources :notices, controller: 'board_notice'
  resources :frees, controller: 'board_free'
  resources :reviews, controller: 'board_review'
  resources :genealogies, controller: 'board_genealogy'
  resources :galleries, controller: 'board_gallery'
  resources :presentations, controller: 'board_presentation'
  resources :documents, controller: 'board_document'
  resources :blogs, controller: 'board_blog'
  resources :lines, controller: 'board_line', only: [:index, :create, :destroy]
  resources :grades, controller: 'board_grade', except: [:index]
  resources :reports, controller: 'board_report'

  # 캘린더
  resources :calendar, except: :new

  # Project
  resources :projects do
    member do
      get 'manage'
      get 'receive'
      get 'approval'
      delete 'leave'
    end
  end

  # 문의
  resources :inquiries, only: [:show, :create, :destroy]

  # Static Pages
  get '/privacy_policy' => 'base#privacy'
  get '/terms_service' => 'base#terms'
  get '/contact' => 'base#contact'
  get '/members' => 'users#index'


  # ADMIN ROUTES
  get '/admin/membership'
  patch '/admin/membership' => 'admin#membership_update'
  put '/admin/membership' => 'admin#membership_update'
  get '/admin/grades'
  patch '/admin/grades' => 'admin#grades_update'
  put '/admin/grades' => 'admin#grades_update'
  get '/admin/inquiries'
  
  # API ROUTES
  namespace :api, path: '/', constraints: { subdomain: 'api' } do
    namespace :v1 do
      get '/authenticate' => 'auth#get_token'
      resources :notices, controller: 'board_notice'
    end
  end

  # , constraints: { subdomain: 'api' }

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/admin/grades.html.erb
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Admin Dashboard</h1>
    </div>
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<!--=== Content Part ===-->
<div class="container content">
    <div class="row">
        <!-- Begin Sidebar Menu -->
        <div class="col-md-3">
            <ul class="list-group sidebar-nav-v1" id="sidebar-nav">

                <!-- 멤버·스텝 -->
                <li class="list-group-item"><a href="<%= admin_membership_path %>">멤버·스텝</a></li>
                <!-- End 멤버·스텝 -->

                <!-- 멤버·스텝 -->
                <li class="list-group-item active"><a href="<%= admin_grades_path %>">등업신청</a></li>
                <!-- End 멤버·스텝 -->

                <!-- 문의관리-->
                <li class="list-group-item"><a href="<%= admin_inquiries_path %>">문의관리</a></li>
                <!-- End 문의관리 -->

                <!-- Maps -->                    
                <li class="list-group-item list-toggle">                   
                    <a class="accordion-toggle" href="#collapse-maps" data-toggle="collapse">Maps</a>
                    <ul id="collapse-maps" class="collapse">
                        <li>
                            <span class="badge badge-u">New</span>
                            <a href="shortcode_maps_google.html"><i class="fa fa-map-marker"></i> Google Maps</a>
                        </li>
                        <li>
                            <span class="badge badge-u">New</span>                            
                            <a href="shortcode_maps_vector.html"><i class="fa fa-align-center"></i> Vector Maps</a>
                        </li>
                    </ul>
                </li>
                <!-- End Maps -->                    

                <!-- Charts -->
                <li class="list-group-item">
                    <span class="badge badge-u">New</span>                    
                    <a href="shortcode_compo_charts.html">Charts &amp; Countdowns</a>
                </li>
                <!-- End Charts -->
            </ul>
        </div>
        <!-- End Sidebar Menu -->

        <!-- Begin Content -->
        <div class="col-md-9">

            <div class="headline"><h2>등업신청 관리</h2></div>

            

            <form action="#" class="sky-form">
                <fieldset>                  
                    <div class="row">
                        <label class="label col col-2">멤버 검색</label>
                        <section class="col col-2">
                            <select class="form-control">
                                <option>ID</option>
                                <option>이름</option>
                            </select>
                        </section>
                        <section class="col col-6">
                            <label class="input">
                                <input type="text">
                            </label>
                        </section>
                        <section class="col col-2"><button type="submit" class="btn-u pull-right">Submit</button></section>
                    </div>
                </fieldset>
            </form>

            <div class="margin-bottom-40"></div>

            <%= form_tag "/admin/grades", method: :patch, class: "sky-form" do %>
                <fieldset>                  
                    <div class="row">
                        <label class="label col col-2">선택 멤버를</label>
                        <section class="col col-3">
                            <%= select_tag "grades[grade]", "<option value='associate_member'>준회원</option><option value='regular_member'>정회원</option><option value='honorary_member'>명예회원</option><option value='president'>회장</option><option value='vice_president'>부회장</option><option value='manager'>총무</option><option value='librian'>도서관리자</option><option value='admin'>서버관리자</option>".html_safe, class: "form-control" %>
                        </section>
                        <label class="label col col-1">(으)로</label>
                        <section class="col col-1"><%= submit_tag "변경", class: "btn-u" %></section>
                        <section class="col col-2"><%= submit_tag "강제 탈퇴", class: "btn-u btn-u-red" %></section>
                    </div>
                </fieldset>
            
                <!--Table Striped-->
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th><input type="checkbox" name="checkbox"></th>
                            <th>IDX</th>
                            <th>ID</th>
                            <th>이름</th>
                            <th>제목</th>
                            <th>신청일</th>
                            <th>등급</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @boards.each do |board| %>
                            <tr>
                                <td><input type="checkbox" name="grades[member][]" value="<%= board.id %>"></td>
                                <td><%= board.id %></td>
                                <td><%= board.user.uid %></td>
                                <td><%= board.user.realname %></td>
                                <td><%= board.title %></td>
                                <td><%= board.created_at.strftime("%Y.%m.%-d") %></td>   
                                <td><%= user_roles(board.user) %></td>
                                <td><%= link_to '<i class="rounded-x fa fa-eye"></i>'.html_safe, grade_path(board) %></td>
                                <td><%= link_to '<i class="rounded-x fa fa-trash"></i>'.html_safe, "/#{board.board_type.name}/#{board.id}", method: :delete, data: { confirm: "정말 삭제 하시겠습니까?" } %></td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
                <!--End Table Striped-->
            <% end %>
        </div>
        <!-- End Content -->
    </div>          
</div><!--/container-->     
<!--=== End Content Part ===-->

app/views/admin/inquiries.html.erb
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Admin Dashboard</h1>
    </div>
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<!--=== Content Part ===-->
<div class="container content">
    <div class="row">
        <!-- Begin Sidebar Menu -->
        <div class="col-md-3">
            <ul class="list-group sidebar-nav-v1" id="sidebar-nav">

                <!-- 멤버·스텝 -->
                <li class="list-group-item"><a href="<%= admin_membership_path %>">멤버·스텝</a></li>
                <!-- End 멤버·스텝 -->

                <!-- 멤버·스텝 -->
                <li class="list-group-item"><a href="<%= admin_grades_path %>">등업신청</a></li>
                <!-- End 멤버·스텝 -->

                <!-- 문의관리-->
                <li class="list-group-item active"><a href="<%= admin_inquiries_path %>">문의관리</a></li>
                <!-- End 문의관리 -->

                <!-- Maps -->                    
                <li class="list-group-item list-toggle">                   
                    <a class="accordion-toggle" href="#collapse-maps" data-toggle="collapse">Maps</a>
                    <ul id="collapse-maps" class="collapse">
                        <li>
                            <span class="badge badge-u">New</span>
                            <a href="shortcode_maps_google.html"><i class="fa fa-map-marker"></i> Google Maps</a>
                        </li>
                        <li>
                            <span class="badge badge-u">New</span>                            
                            <a href="shortcode_maps_vector.html"><i class="fa fa-align-center"></i> Vector Maps</a>
                        </li>
                    </ul>
                </li>
                <!-- End Maps -->                    

                <!-- Charts -->
                <li class="list-group-item">
                    <span class="badge badge-u">New</span>                    
                    <a href="shortcode_compo_charts.html">Charts &amp; Countdowns</a>
                </li>
                <!-- End Charts -->
            </ul>
        </div>
        <!-- End Sidebar Menu -->

        <!-- Begin Content -->
        <div class="col-md-9">

            <div class="headline"><h2>문의관리</h2></div>

            <div class="margin-bottom-40"></div>

            <!--Table Striped-->
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>IDX</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Date</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @inquiries.each do |inquiry| %>
                        <tr>
                            <td><%= inquiry.id %></td>
                            <td><%= inquiry.name %></td>
                            <td><%= inquiry.email %></td>
                            <td><%= inquiry.created_at.strftime("%Y.%m.%-d") %></td>
                            <td><%= link_to '<i class="rounded-x fa fa-eye"></i>'.html_safe, inquiry_path(inquiry) %></td>
                            <td><%= link_to '<i class="rounded-x fa fa-trash"></i>'.html_safe, inquiry_path(inquiry), method: :delete, data: { confirm: "정말 삭제 하시겠습니까?" } %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            <!--End Table Striped-->
        </div>
        <!-- End Content -->
    </div>          
</div><!--/container-->     
<!--=== End Content Part ===-->

app/views/admin/membership.html.erb
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Admin Dashboard</h1>
    </div>
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<!--=== Content Part ===-->
<div class="container content">
    <div class="row">
        <!-- Begin Sidebar Menu -->
        <div class="col-md-3">
            <ul class="list-group sidebar-nav-v1" id="sidebar-nav">

                <!-- 멤버·스텝 -->
                <li class="list-group-item active"><a href="<%= admin_membership_path %>">멤버·스텝</a></li>
                <!-- End 멤버·스텝 -->

                <!-- 멤버·스텝 -->
                <li class="list-group-item"><a href="<%= admin_grades_path %>">등업신청</a></li>
                <!-- End 멤버·스텝 -->

                <!-- 문의관리-->
                <li class="list-group-item"><a href="<%= admin_inquiries_path %>">문의관리</a></li>
                <!-- End 문의관리 -->

                <!-- Maps -->                    
                <li class="list-group-item list-toggle">                   
                    <a class="accordion-toggle" href="#collapse-maps" data-toggle="collapse">Maps</a>
                    <ul id="collapse-maps" class="collapse">
                        <li>
                            <span class="badge badge-u">New</span>
                            <a href="shortcode_maps_google.html"><i class="fa fa-map-marker"></i> Google Maps</a>
                        </li>
                        <li>
                            <span class="badge badge-u">New</span>                            
                            <a href="shortcode_maps_vector.html"><i class="fa fa-align-center"></i> Vector Maps</a>
                        </li>
                    </ul>
                </li>
                <!-- End Maps -->                    

                <!-- Charts -->
                <li class="list-group-item">
                    <span class="badge badge-u">New</span>                    
                    <a href="shortcode_compo_charts.html">Charts &amp; Countdowns</a>
                </li>
                <!-- End Charts -->
            </ul>
        </div>
        <!-- End Sidebar Menu -->

        <!-- Begin Content -->
        <div class="col-md-9">

            <div class="headline"><h2>전체 멤버 관리</h2></div>

            

            <form action="#" class="sky-form">
                <fieldset>                  
                    <div class="row">
                        <label class="label col col-2">멤버 검색</label>
                        <section class="col col-2">
                            <select class="form-control">
                                <option>ID</option>
                                <option>이름</option>
                            </select>
                        </section>
                        <section class="col col-6">
                            <label class="input">
                                <input type="text">
                            </label>
                        </section>
                        <section class="col col-2"><button type="submit" class="btn-u pull-right">Submit</button></section>
                    </div>
                </fieldset>
            </form>

            <div class="margin-bottom-40"></div>

            <%= form_tag "/admin/membership", method: :patch, class: "sky-form" do %>
                <fieldset>                  
                    <div class="row">
                        <label class="label col col-2">선택 멤버를</label>
                        <section class="col col-3">
                            <%= select_tag "membership[grade]", "<option value='associate_member'>준회원</option><option value='regular_member'>정회원</option><option value='honorary_member'>명예회원</option><option value='president'>회장</option><option value='vice_president'>부회장</option><option value='manager'>총무</option><option value='librian'>도서관리자</option><option value='admin'>서버관리자</option>".html_safe, class: "form-control" %>
                        </section>
                        <label class="label col col-1">(으)로</label>
                        <section class="col col-1"><%= submit_tag "변경", class: "btn-u" %></section>
                        <section class="col col-2"><%= submit_tag "강제 탈퇴", class: "btn-u btn-u-red" %></section>
                        <section class="col col-3">
                            <select class="form-control">
                                <option>전체 멤버</option>
                                <option>준회원</option>
                                <option>정회원</option>
                                <option>명예회원</option>
                                <option>회장</option>
                                <option>부회장</option>
                                <option>총무</option>
                                <option>도서관리자</option>
                                <option>서버관리자</option>
                            </select>
                        </section>
                    </div>
                </fieldset>
            
                <!--Table Striped-->
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th><input type="checkbox" name="checkbox"></th>
                            <th>IDX</th>
                            <th>ID</th>
                            <th>이름</th>
                            <th>등급</th>
                            <th>가입일</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @users.each do |user| %>
                            <tr>
                                <td><input type="checkbox" name="membership[member][]" value="<%= user.id %>"></td>
                                <td><%= user.id %></td>
                                <td><%= user.uid %></td>
                                <td><%= user.realname %></td>
                                <td><%= user_roles(user) %></td>
                                <td><%= user.created_at.strftime("%Y.%m.%-d") %></td>                          
                            </tr>
                        <% end %>
                    </tbody>
                </table>
                <!--End Table Striped-->
            <% end %>
        </div>
        <!-- End Content -->
    </div>          
</div><!--/container-->     
<!--=== End Content Part ===-->