config/routes.rb
Rails.application.routes.draw do

  # GENERAL ROUTES
  root 'board_line#index'

  devise_for :users
  resources :users, only: [:show, :update] do
    member do
      patch 'update_avatar'
      put 'update_avatar'
      post 'like'
      delete 'unlike'
    end

    resources :profile, only: [:index]
    # 프로필 정보 수정 (닉네임, 한줄소개)
    put   '/profile' => 'profile#update'
    patch '/profile' => 'profile#update'
    # Social 정보 수정
    post  '/social'  => 'profile#social'
  end
  # S Finger login
  get '/sfinger' => 'users#sfinger'
  post '/sfinger' => 'users#sfinger_register'

  # 게시판 형태
  resources :boards, only: [] do
    resources :comments, only: [:create, :edit, :destroy, :update]
  end
  resources :notices, controller: 'board_notice'
  resources :frees, controller: 'board_free'
  resources :reviews, controller: 'board_review'
  resources :genealogies, controller: 'board_genealogy'
  resources :galleries, controller: 'board_gallery'
  resources :presentations, controller: 'board_presentation'
  resources :documents, controller: 'board_document'
  resources :blogs, controller: 'board_blog'
  resources :lines, controller: 'board_line', only: [:index, :create, :destroy]
  resources :grades, controller: 'board_grade', except: [:index]
  resources :reports, controller: 'board_report'

  # 캘린더
  resources :calendar, except: :new

  # Project
  resources :projects do
    member do
      get 'manage'
      get 'receive'
      get 'approval'
      delete 'leave'
    end
  end

  # 문의
  resources :inquiries, only: [:show, :create, :destroy]

  # Static Pages
  get '/privacy_policy' => 'base#privacy'
  get '/terms_service' => 'base#terms'
  get '/contact' => 'base#contact'
  get '/members' => 'users#index'


  # ADMIN ROUTES
  get '/admin/membership'
  patch '/admin/membership' => 'admin#membership_update'
  put '/admin/membership' => 'admin#membership_update'
  get '/admin/grades'
  patch '/admin/grades' => 'admin#grades_update'
  put '/admin/grades' => 'admin#grades_update'
  get '/admin/inquiries'
  
  # API ROUTES
  namespace :api, path: '/', constraints: { subdomain: 'api' } do
    namespace :v1 do
      get '/authenticate' => 'auth#get_token'
      resources :notices, controller: 'board_notice'
    end
  end

  # , constraints: { subdomain: 'api' }

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  default_scope -> { order('created_at DESC') }
  include Authority::UserAbilities
  include Tokenable
  has_many :likes, dependent: :destroy
  has_many :boards, dependent: :nullify
  has_many :comments, dependent: :nullify

  # Project N:M Association
  has_many :user_project_mappeds
  has_many :projects, through: "user_project_mappeds"

  has_attached_file :avatar,
    :path => ":rails_root/public/avatar/:id/:filename",
    :url  => "/avatar/:id/:filename",
    :default_url => "bootstrap/testimonials/user.jpg"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :uid, presence: true, uniqueness: { case_sensitive: false }
  validates :realname ,presence: true
  validates :phone ,presence: true, length: { is: 11 }

  # paperclip validations
  validates_attachment_content_type :avatar, :content_type => /^image\/(jpeg|jpg|png|gif)$/
  validates_attachment_size :avatar, :in => 0..10.megabytes

  after_create :init_user

  def like?(board)
    likes.find_by(board: board).present?
  end
 
  def like!(board)
    likes.create!(board: board)
  end
 
  def unlike!(board)
    likes.find_by(board: board).destroy
  end

  def share?(board)
    likes.find_by(board: board).present?
  end
 
  def share!(board)
    shares.create!(board: board)
  end

  def member?
    has_role?(:regular_member) || has_role?(:honorary_member) || operator?
  end

  def operator?
    has_role?(:president) || has_role?(:vice_president) || has_role?(:manager) || has_role?(:librarian) || has_role?(:admin)
  end

  private
  
  def init_user
    add_role :regular_member if User.count > 1 
    self.nickname = self.uid
    self.save
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, except: [:index, :sfinger, :sfinger_register]

	def index
	end
	
	def show
		@user   = User.where(uid: params[:id]).first

		redirect_to root_path unless @user.present?

		@boards = @user.boards.where(board_type: BoardType.where(name: "frees").first)

		# pagination
		@page   	= params[:page].present? ? params[:page].to_i : 1
		@page_max	= (@boards.count-1) / 4 + 1 if @boards.present?
		@boards 	= @boards.paginate(:page => params[:page], :per_page => 4)

		respond_to do |format|
			format.html
			format.js
		end
	end

	def update_avatar
		@user = User.where(uid: params[:id]).first

		if @user.present?
			@user.avatar = params[:user][:avatar]
			@user.save
		end

		redirect_to :back
	end

	def like
		@board = Board.find_by_id(params[:board_id])
		@call  = nil
		if params[:board_type].present?
			@call = "timeline"
		end
		current_user.like!(@board)

		respond_to do |format|
			format.js
		end
	end

	def unlike
		@board = Board.find_by_id(params[:board_id])
		if params[:board_type].present?
			@call = "timeline"
		end
		current_user.unlike!(@board)

		respond_to do |format|
			format.js
		end
	end

	def sfinger
	end

	def sfinger_register
		now = DateTime.now

		@user = User.where(uid: params[:id]).first

		unless @user.present?
			puts "Users#sfinger_register - create new user"
			pw = Devise.friendly_token.first(20)
			@user = User.create!(
				uid: params[:id],
				realname: params[:id],
				email: params[:email],
				phone: params[:phone],
				created_at: now,
				updated_at: now,
				password: pw,
				password_confirmation: pw,
				provider: "s-finger"
			)
		end

		puts @user.id

		sign_in @user
		respond_to do |format|
			format.js { render js: "document.location = '#{root_path}'" }
			format.html { redirect_to root_path }
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_like.html.erb
<%= form_for(current_user, url: like_user_path(current_user), method: :post, remote: true, authenticity_token: true, html: {id: "like_form_#{board.id}"}) do |f| %>
	    <i class="fa fa-heart"></i> <%= board.likes.count %>
	<input type="hidden" name="board_id" value="<%= board.id %>" />
	<input type="hidden" name="board_type" value="users_timeline" />
<% end %>

app/views/users/_timeline.html.erb
<li <%= "class=timeline-inverted" if board_counter.odd? %>>
    <div class="timeline-badge primary"><i class="glyphicon glyphicon-record"></i></div>
    <div class="timeline-panel">
        <div class="timeline-heading">
            <% images = board.attachments.where("lower(contents_content_type) LIKE ?", "image%") %>
            <% images_count = images.count %>
            <% if images_count > 1 %>
                <div class="carousel slide carousel-v1" id="myCarousel<%= board.id %>">
                    <div class="carousel-inner">
                        <% images.each_with_index do |image, index| %>
                        <div class="<%= index == 0 ? 'item active' : 'item' %>">
                            <%= image_tag image.contents.url, class: "img-responsive", style: "width: 386.313px;height: 244px;" %>
                        </div>
                        <% end %>
                    </div>
                    
                    <div class="carousel-arrow">
                        <a data-slide="prev" href="#myCarousel<%= board.id %>" class="left carousel-control">
                            <i class="fa fa-angle-left"></i>
                        </a>
                        <a data-slide="next" href="#myCarousel<%= board.id %>" class="right carousel-control">
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </div>
                </div>
            <% elsif images_count == 1 %>
                <%= image_tag images.first.contents.url, class: "img-responsive", style: "width: 386.313px;height: 244px;" %>
            <% else %>
                <img class="img-responsive" src="/assets/bootstrap/main/img10.jpg" alt=""/>
            <% end %>
        </div>
        <div class="timeline-body text-justify">
            <h2><a href="/frees/<%= board.id %>"><%= board.title %></a></h2>
            <p><%= truncate((strip_tags board.contents), length: 100, separator: ' ', escape: false) %></p>
            <a class="btn-u btn-u-sm" href="/frees/<%= board.id %>">Read More</a>
        </div>
        <div class="timeline-footer">
            <ul class="list-unstyled list-inline blog-info">
                <li><i class="fa fa-clock-o"></i> <%= board.created_at.strftime("%B %-d, %Y") %></li>
                <li><i class="fa fa-comments-o"></i> <a href="/notices/<%= board.id %>#comments"><%= board.comments.count %> Comments</a></li>
            </ul>
            <a class="likes" href="javascript:{};" id="likes_<%= board.id %>" onclick="$('#like_form_<%= board.id %>').submit();">
                <% if current_user.like?(board) %>
                    <%= render 'unlike', board: board %>
                <% else %>
                    <%= render 'like', board: board %>
                <% end %>
            </a>
        </div>
    </div>
</li>

app/views/users/_unlike.html.erb
<%= form_for(current_user, url: unlike_user_path(current_user), method: :delete, remote: true, authenticity_token: true, html: {id: "like_form_#{board.id}"}) do |f| %>
	<i class="fa fa-heart" style="color:#72c02c;"></i> <%= board.likes.count %>
	<input type="hidden" name="board_id" value="<%= board.id %>" />
	<input type="hidden" name="board_type" value="users_timeline" />
<% end %>

app/views/users/index.html.erb
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Members</h1>
    </div>
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<div class="margin-bottom-60"></div>

<!--=== Team v5 ===-->
<div class="container">
    <div class="headline-center margin-bottom-60">
        <h2>ACCOUNT DIRECTORS</h2>
        <p>Phasellus vitae ipsum ex. Etiam eu vestibulum ante. <br>
        Lorem ipsum <strong>dolor</strong> sit amet, consectetur adipiscing elit. Morbi libero libero, imperdiet fringilla </p>
    </div>

    <div class="row team-v5 margin-bottom-30">
        <div class="col-sm-4 sm-margin-bottom-50">
            <div class="team-img">
                <img class="img-responsive" src="/assets/bootstrap/team/img1-md.jpg" alt="">
                <div class="team-hover">
                    <ul class="list-inline team-social-v5">
                        <li><a href="#"><i class="rounded-x fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="rounded-x fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="rounded-x fa fa-google-plus"></i></a></li>
                    </ul>
                </div>
            </div>
            <span>Marketing</span>
            <small>Technical Director</small>
            <p>Pellentesque habitant morbi tristique senectus netus et malesuada fames ac turpis egestas.</p>
        </div>
        <div class="col-sm-4 sm-margin-bottom-50">
            <div class="team-img">
                <img class="img-responsive" src="/assets/bootstrap/team/img5-md.jpg" alt="">
                <div class="team-hover">
                    <ul class="list-inline team-social-v5">
                        <li><a href="#"><i class="rounded-x fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="rounded-x fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="rounded-x fa fa-google-plus"></i></a></li>
                    </ul>
                </div>
            </div>
            <span>Sara Lisbon</span>
            <small>Developer</small>
            <p>Pellentesque habitant morbi tristique senectus netus et malesuada fames ac turpis egestas.</p>
        </div>
        <div class="col-sm-4">
            <div class="team-img">
                <img class="img-responsive" src="/assets/bootstrap/team/img3-md.jpg" alt="">
                <div class="team-hover">
                    <ul class="list-inline team-social-v5">
                        <li><a href="#"><i class="rounded-x fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="rounded-x fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="rounded-x fa fa-google-plus"></i></a></li>
                    </ul>
                </div>
            </div>
            <span>John Doe</span>
            <small>Designer</small>
            <p>Pellentesque habitant morbi tristique senectus netus et malesuada fames ac turpis egestas.</p>
        </div>
    </div><!--/end team v5-->
</div>
<!--=== End Team v5 ===-->

<hr class="margin-bottom-60">

<!--=== Team v6 ===-->
<div class="container">
    <div class="headline-center margin-bottom-60">
        <h2>OTHER MEMBERS</h2>
        <p>Phasellus vitae ipsum ex. Etiam eu vestibulum ante. <br>
        Lorem ipsum <strong>dolor</strong> sit amet, consectetur adipiscing elit. Morbi libero libero, imperdiet fringilla </p>
    </div>

    <div class="row team-v6 margin-bottom-60">
        <div class="col-md-3 col-sm-6 md-margin-bottom-50">
            <img class="img-responsive" src="/assets/bootstrap/team/img6-md.jpg" alt="">
            <span>Marketing</span>
            <small>Graphic Designer</small>
            <ul class="list-inline social-icons-v1">
                <li><a href="#"><i class="rounded-x fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="rounded-x fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="rounded-x fa fa-google-plus"></i></a></li>
            </ul>
        </div>
        <div class="col-md-3 col-sm-6 md-margin-bottom-50">
            <img class="img-responsive" src="/assets/bootstrap/team/img4-md.jpg" alt="">
            <span>Sara Lisbon</span>
            <small>Community</small>
            <ul class="list-inline social-icons-v1">
                <li><a href="#"><i class="rounded-x fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="rounded-x fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="rounded-x fa fa-google-plus"></i></a></li>
            </ul>
        </div>
        <div class="col-md-3 col-sm-6 sm-margin-bottom-50">
            <img class="img-responsive" src="/assets/bootstrap/team/img2-md.jpg" alt="">
            <span>John Doe</span>
            <small>Support</small>
            <ul class="list-inline social-icons-v1">
                <li><a href="#"><i class="rounded-x fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="rounded-x fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="rounded-x fa fa-google-plus"></i></a></li>
            </ul>
        </div>
        <div class="col-md-3 col-sm-6">
            <img class="img-responsive" src="/assets/bootstrap/team/img1-md.jpg" alt="">
            <span>Alice Williams</span>
            <small>Marketing</small>
            <ul class="list-inline social-icons-v1">
                <li><a href="#"><i class="rounded-x fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="rounded-x fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="rounded-x fa fa-google-plus"></i></a></li>
            </ul>
        </div>
    </div><!--/end team v6-->

    <div class="row team-v6 margin-bottom-60">
        <div class="col-md-3 col-sm-6 md-margin-bottom-50">
            <img class="img-responsive" src="/assets/bootstrap/team/img3-md.jpg" alt="">
            <span>Marketing</span>
            <small>Graphic Designer</small>
            <ul class="list-inline social-icons-v1">
                <li><a href="#"><i class="rounded-x fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="rounded-x fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="rounded-x fa fa-google-plus"></i></a></li>
            </ul>
        </div>
        <div class="col-md-3 col-sm-6 md-margin-bottom-50">
            <img class="img-responsive" src="/assets/bootstrap/team/img7-md.jpg" alt="">
            <span>Sara Lisbon</span>
            <small>Community</small>
            <ul class="list-inline social-icons-v1">
                <li><a href="#"><i class="rounded-x fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="rounded-x fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="rounded-x fa fa-google-plus"></i></a></li>
            </ul>
        </div>
        <div class="col-md-3 col-sm-6 sm-margin-bottom-50">
            <img class="img-responsive" src="/assets/bootstrap/team/img1-md.jpg" alt="">
            <span>John Doe</span>
            <small>Support</small>
            <ul class="list-inline social-icons-v1">
                <li><a href="#"><i class="rounded-x fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="rounded-x fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="rounded-x fa fa-google-plus"></i></a></li>
            </ul>
        </div>
        <div class="col-md-3 col-sm-6">
            <img class="img-responsive" src="/assets/bootstrap/team/img5-md.jpg" alt="">
            <span>Alice Williams</span>
            <small>Marketing</small>
            <ul class="list-inline social-icons-v1">
                <li><a href="#"><i class="rounded-x fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="rounded-x fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="rounded-x fa fa-google-plus"></i></a></li>
            </ul>
        </div>
    </div><!--/end team v6-->
</div>
<!--=== End Team v6 ===-->

app/views/users/like.js.erb
<% if @board.board_type.name.eql?("lines") %>
$('#likes_<%= @board.id %>').html("<%=j render 'board_line/unlike', board: @board %>");
$('#likes_count_<%= @board.id %>').html("<%= @board.likes.count %> Likes");
$('#likes_count_<%= @board.id %>').attr("data-original-title", "<%= @board.like_members.limit(3).map(&:realname).join(', ') %><%= ' 외 '+ (@board.likes.count - 3).to_s + '명' if @board.likes.count > 3 %>");
<% elsif @call.eql?("timeline") %>
$('#likes_<%= @board.id %>').html("<%=j render 'users/unlike', board: @board %>");
<% else %>
$('#likes_<%= @board.id %>').html("<%=j render 'boards/unlike', board: @board %>");
<% end %>

app/views/users/sfinger.html.erb
<style type="text/css">
	/* Start by setting display:none to make this hidden.
	   Then we position it in relation to the viewport window
	   with position:fixed. Width, height, top and left speak
	   for themselves. Background we set to 80% white with
	   our animation centered, and no-repeating */
	.modal {
	    display:    none;
	    position:   fixed;
	    z-index:    1000;
	    top:        0;
	    left:       0;
	    height:     100%;
	    width:      100%;
	    background: #4A3E3E
	                url('/assets/bootstrap/ajax-loader.gif') 
	                50% 50% 
	                no-repeat;
	    opacity: 0.7;
	}

	/* When the body has the loading class, we turn
	   the scrollbar off with overflow:hidden */
	body.loading {
	    overflow: hidden;   
	}

	/* Anytime the body has the loading class, our
	   modal element will be visible */
	body.loading .modal {
	    display: block;
	}
</style>

<div id="s_finger_login" style="display:none;"></div>
<div class="modal"></div>
<script type="text/javascript">
	$body = $("body");
	$body.addClass("loading")

    var s_finger_login = new s_finger_login("rm81FvNAQKo58MjWyRqU", "https://cert-is.ga/sfinger");
    // s_finger_login.setDomain(".service.com");
    s_finger_login.setState("abcdefghijkmnopqrst");
    // s_finger_login.setPopup();
    s_finger_login.setButton("blue",3,36);
    s_finger_login.init_s_finger_login();
    s_finger_login.get_s_finger_userprofile(s_callback);

    function s_callback() {
        var id    = s_finger_login.getProfileData('id');
        var email = s_finger_login.getProfileData('email');
        var phone = s_finger_login.getProfileData('phone');

        console.log(id)
        console.log(email)
        console.log(phone)

        $.ajax({
            type: "POST",
            url: "/sfinger",
            cache: false,
            data: {
            	id: id,
            	email: email,
            	phone: phone
            },
            success : {},
            error: {}
        })
    }
</script>

app/views/users/show.html.erb
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">타임라인</h1>
        <!--
        <ul class="pull-right breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li><a href="">Blog</a></li>
            <li class="active">Blog Item 2</li>
        </ul>
        -->
    </div>
</div><!--/breadcrumbs-->
<!--=== Profile ===-->
<div class="container content profile">
	<div class="row">
        <!--Left Sidebar-->
        <div class="col-md-3 md-margin-bottom-40">
            <%= image_tag @user.avatar.url, class: "img-responsive profile-img margin-bottom-20", style: "height:264px;" %>

            <div class="panel-heading-v1 overflow-h">
                <h1 class="heading-xs"> <%= @user.uid %> </h1> 
                <p> <%= @user.realname %> </p>
            </div>
            <hr>

            <ul class="list-group sidebar-nav-v1 margin-bottom-40" id="sidebar-nav-1">
                <li class="list-group-item active">
                    <a href="<%= user_path(@user.uid) %>"><i class="fa fa-bar-chart-o"></i> Timeline</a>
                </li>
                <li class="list-group-item">
                    <a href="<%= user_profile_index_path(@user.uid) %>"><i class="fa fa-user"></i> Profile</a>
                </li>                                       
                <li class="list-group-item">
                    <a href="#"><i class="fa fa-cubes"></i> My Projects</a>
                </li>
                <li class="list-group-item">
                    <a href="#"><i class="fa fa-comments"></i> Comments</a>
                </li>
                <li class="list-group-item">
                    <a href="#"><i class="fa fa-cog"></i> Settings</a>
                </li> 
            </ul>   

            <hr>

            <div class="panel panel-profile">
                <div class="panel-heading overflow-h">
                    <h2 class="panel-title heading-sm pull-left"><i class="fa fa-lightbulb-o"></i> Social Contacts </h2>
                    <a href="#"><i class="fa fa-cog pull-right"></i></a>
                </div>
                <div class="panel-body">
                    <ul class="list-unstyled social-contacts-v3">
                        <li><i class="rounded-x tw fa fa-twitter"></i> <a href="#">edward.rooster</a></li>
                        <li><i class="rounded-x fb fa fa-facebook"></i> <a href="#">Edward Rooster</a></li>
                        <li><i class="rounded-x gh fa fa-github"></i> <a href="#">edwardRooster77</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!--End Left Sidebar-->

        <!-- Profile Content -->            
        <!-- Begin Content -->
            <div class="col-md-9">
                <% if @boards.present? %>
                <ul class="timeline-v1">
                    <%= render partial: 'timeline', collection: @boards, as: :board %>
                    <li class="clearfix" style="float: none;"></li>
                </ul>
                <%= link_to "Load More", "/users/admin?page=#{@page+1}", class: "btn-u btn-u-default btn-block", remote: true, id: "timeline_loadmore", style: "color: #fff;" unless @page.equal?(@page_max) %>
                <% else %>
                    <div class="error-v1">
                        <span class="error-v1-title">Empty</span>
                        <span>검색 결과 없음!</span>
                        <p>아래의 글쓰기 버튼을 통해 새 글을 작성해 주세요.</p>
                        <a class="btn-u btn-bordered" href="/frees/new">Go! Go!</a>
                    </div>
                <% end %>
            </div>
            <!-- End Content -->
        <!-- End Profile Content -->            
    </div>
</div><!--/container-->    
<!--=== End Profile ===-->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.initScrollBar();
        });
</script>

app/views/users/show.js.erb
$("<%=j render partial: 'timeline', collection: @boards, as: :board %>").insertAfter($('.timeline-v1>li:nth-last-child(2)'));

<% if @page.equal?(@page_max) %>
	$('#timeline_loadmore').fadeOut();
	$('#timeline_loadmore').remove();
<% else %>
	var href = $('#timeline_loadmore').attr("href");
	href     = parseInt( href.slice(-1) ) + 1 
	href     = "/users/admin?page=" + href
	$('#timeline_loadmore').attr("href", href);
<% end %>

app/views/users/unlike.js.erb
<% if @board.board_type.name.eql?("lines") %>
$('#likes_<%= @board.id %>').html("<%=j render 'board_line/like', board: @board %>");
$('#likes_count_<%= @board.id %>').html("<%= @board.likes.count %> Likes");
$('#likes_count_<%= @board.id %>').attr("data-original-title", "<%= @board.like_members.limit(3).map(&:realname).join(', ') %><%= ' 외 '+ (@board.likes.count - 3).to_s + '명' if @board.likes.count > 3 %>");
<% elsif @call.eql?("timeline") %>
$('#likes_<%= @board.id %>').html("<%=j render 'users/like', board: @board %>");
<% else %>
$('#likes_<%= @board.id %>').html("<%=j render 'boards/like', board: @board %>");
<% end %>