config/routes.rb
Rails.application.routes.draw do

  # GENERAL ROUTES
  root 'board_line#index'

  devise_for :users
  resources :users, only: [:show, :update] do
    member do
      patch 'update_avatar'
      put 'update_avatar'
      post 'like'
      delete 'unlike'
    end

    resources :profile, only: [:index]
    # 프로필 정보 수정 (닉네임, 한줄소개)
    put   '/profile' => 'profile#update'
    patch '/profile' => 'profile#update'
    # Social 정보 수정
    post  '/social'  => 'profile#social'
  end
  # S Finger login
  get '/sfinger' => 'users#sfinger'
  post '/sfinger' => 'users#sfinger_register'

  # 게시판 형태
  resources :boards, only: [] do
    resources :comments, only: [:create, :edit, :destroy, :update]
  end
  resources :notices, controller: 'board_notice'
  resources :frees, controller: 'board_free'
  resources :reviews, controller: 'board_review'
  resources :genealogies, controller: 'board_genealogy'
  resources :galleries, controller: 'board_gallery'
  resources :presentations, controller: 'board_presentation'
  resources :documents, controller: 'board_document'
  resources :blogs, controller: 'board_blog'
  resources :lines, controller: 'board_line', only: [:index, :create, :destroy]
  resources :grades, controller: 'board_grade', except: [:index]
  resources :reports, controller: 'board_report'

  # 캘린더
  resources :calendar, except: :new

  # Project
  resources :projects do
    member do
      get 'manage'
      get 'receive'
      get 'approval'
      delete 'leave'
    end
  end

  # 문의
  resources :inquiries, only: [:show, :create, :destroy]

  # Static Pages
  get '/privacy_policy' => 'base#privacy'
  get '/terms_service' => 'base#terms'
  get '/contact' => 'base#contact'
  get '/members' => 'users#index'


  # ADMIN ROUTES
  get '/admin/membership'
  patch '/admin/membership' => 'admin#membership_update'
  put '/admin/membership' => 'admin#membership_update'
  get '/admin/grades'
  patch '/admin/grades' => 'admin#grades_update'
  put '/admin/grades' => 'admin#grades_update'
  get '/admin/inquiries'
  
  # API ROUTES
  namespace :api, path: '/', constraints: { subdomain: 'api' } do
    namespace :v1 do
      get '/authenticate' => 'auth#get_token'
      resources :notices, controller: 'board_notice'
    end
  end

  # , constraints: { subdomain: 'api' }

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/project.rb
class Project < ActiveRecord::Base
	default_scope -> { order('created_at DESC') }
	
	has_many :user_project_mappeds, dependent: :destroy
	has_many :users, through: :user_project_mappeds

	validates :title, presence: true, length: { maximum: 255 }
    validates :description, presence: true, length: { maximum: 3000 }
    validates :start_date, presence: true, length: { maximum: 255 }
    validates :end_date, presence: true, length: { maximum: 255 }

    def master
    	users.where(
			"user_project_mappeds.master = ?",
			true
		).first
	end

	def members
		users.where(
			"user_project_mappeds.approval = ?",
			true
		)
	end

	def joined?(user)
		users.include?(user)
	end

	def unreceived
		users.where(
			"user_project_mappeds.approval = ?",
			false
		)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :authenticate_user!
	before_action :get_project, except: [:index, :new]

	def index
		@projects = Project.all
	end

	def new
		@project = current_user.projects.new
	end

	def create
		@project = current_user.projects.new(project_params)
		if @project.save
			UserProjectMapped.create(
				user: current_user,
				project: @project,
				master: true,
				approval: true
			)
			redirect_to @project
		else
			render 'new'
		end
	end

	def show
		redirect_to root_path unless @project.present?
		@project.update_attributes(views: @project.views+1)
	end

	def edit
	end

	def update
		@project.update_attributes(
			rating1: true,
			rating2: false,
			rating3: false,
			rating4: false,
			rating5: false
		)
		@project.update!(project_params)
		redirect_to @project
	end

	def destroy
		@project.destroy
		redirect_to projects_path
	end

	# 승인요청
	def receive
		@project.user_project_mappeds.create(
			user: current_user,
			master: false,
			approval: false
		)
		redirect_to @project
	end

	# 승인허가
	def approval
		@project.user_project_mappeds
		 		.where(user_id: params[:user_id])
		 		.first
		 		.update_attributes(approval: true)
		redirect_to manage_project_path
	end

	# 멤버 강퇴
	def leave
		@project.user_project_mappeds
		 		.where(user_id: params[:user_id])
		 		.first
		 		.destroy
		redirect_to manage_project_path
	end

	# 승인 및 멤버 관리
	def manage
		@unreceiveds = @project.unreceived
		@members     = @project.members
	end

	private

	def get_project
		@project = Project.where(id: params[:id]).first
	end

	def project_params
		params.require(:project).permit(
			:title,
			:description,
			:start_date,
			:end_date,
			:rating1,
			:rating2,
			:rating3,
			:rating4,
			:rating5
		)
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_noresults.html.erb
<!--=== Content Part ===-->
<div class="container content">     
    <!--Error Block-->
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="error-v1">
                <span class="error-v1-title">Empty</span>
                <span>검색 결과 없음!</span>
                <p>우측 하단의 글쓰기 버튼을 통해 새 프로젝트를 등록해 주세요.</p>
                <a class="btn-u btn-bordered" href="<%= root_path %>">Back Home</a>
            </div>
        </div>
    </div>
    <!--End Error Block-->
</div>  
<!--=== End Content Part ===-->

<!--=== FAQ Content ===-->
<div class="container content-sm">
    <div class="row equal-height-columns margin-bottom-40">
        <div class="col-sm-4 no-space">
            <div class="easy-block-v3 equal-height-column first">
                <i class="fa fa-headphones"></i>
                <div class="inner-faq-b">
                    <h3>Contact Us</h3>
                    <h4>010-****-****</h4>
                    <p>우측 하단의 문의입력란 혹은 이메일을 통해 CERT-IS 운영진 연락처를 문의해주세요.</p>
                </div>    
            </div>
        </div>    
        <div class="col-sm-4 no-space">
            <div class="easy-block-v3 equal-height-column second">
                <i class="icon-cursor"></i>
                <div class="inner-faq-b">
                    <h3>Email Us</h3>
                    <h4>contact@cert-is.kr</h4>
                    <p>우측 하단의 문의입력란 혹은 이메일을 통해 문의를 주시면 빠른 시일 내에 답변을 드리도록 하겠습니다.</p>
                </div>    
            </div>
        </div>    
        <div class="col-sm-4 no-space">
            <div class="easy-block-v3 equal-height-column third">
                <i class="icon-support"></i>
                <div class="inner-faq-b">
                    <h3>Support</h3>
                    <h4>Technical Support</h4>
                    <p>정회원은 REPORT 게시판을 활용해주세요. 준회원인 경우 문의입력란 혹은 이메일을 통해 제보해주세요.</p>
                </div>    
            </div>
        </div>    
    </div>

    <div class="row">
        <div class="col-md-6 col-sm-6">
            <!-- Google Map -->
            <div id="map" class="map">
            </div>
            <!-- End Google Map -->
        </div>
        <div class="col-md-6 col-sm-6">
            <!-- Business Hours -->
            <h3>Get In Touch</h3>
            <ul class="list-inline">
                <li>이메일을 정확히 기입하셔야 답장을 드릴 수 있습니다. <br> 본인정보를 입력해주시면 더 정확히 도와드릴 수 있습니다.</li>
            </ul>

            <hr>

            <%= form_for Inquiry.new do |f| %>
            <div class="row">
                <div class="col-sm-6">
                    <div class="input-group margin-bottom-10">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        <%= f.text_field :name, class: "form-control", placeholder: "Name", maxlength: "255" %>
                    </div>    
                </div>
                <div class="col-sm-6">
                    <div class="input-group margin-bottom-20">
                        <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                        <%= f.email_field :email, class: "form-control", placeholder: "Email", maxlength: "255" %>
                    </div>    
                </div>
            </div>    
            <%= f.text_area :content, class: "form-control margin-bottom-20", rows: "5", placeholder: "Type your question here...", maxlength: "1000" %>
            <button class="btn-u btn-u-sm pull-right" type="submit">Send question</button>
            <% end %>
        </div>
    </div>
</div><!--/container-->
<!--=== End FAQ Content ===-->

app/views/projects/edit.html.erb
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Projects</h1>
    </div>
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<div class="bg-color-light">
    <div class="container content-sm">
        <div class="tag-box tag-box-v3 form-page">
            <div class="headline"><h3>New Project</h3></div>                
            <%= form_for @project, html: {class: "sky-form", style: "border:none;"} do |f| %>
                <!--Inputs-->
                <h4>* 주제</h4>
                <div id="board-title" class=""> 
                    <%= f.text_field :title , class: "form-control", maxlength: "255" %>
                </div>
                <!--End Inputs-->

                <div class="margin-bottom-40"></div>

                <h4>* 프로젝트 진행 기간</h4>
                <div class="row">
                	<div class="col-lg-3" id="sandbox-container"><%= f.text_field :start_date, class: 'form-control', maxlength: "255" %>
	            		<em id="end_day_required" style='font-style: normal;font-size: 11px;line-height: 15px;color: #ee9393; display:none;'>This is a required field.</em>
	            	</div>
	            	<div class="col-lg-1" style="text-align:center;"><p>~</p></div>
	                <div class="col-lg-3" id="sandbox-container2"><%= f.text_field :end_date, class: 'form-control', maxlength: "255" %>
	            		<em id="end_day_required" style='font-style: normal;font-size: 11px;line-height: 15px;color: #ee9393; display:none;'>This is a required field.</em>
	            	</div>
	            </div>

                <div class="margin-bottom-40"></div>

                <section>
                    <div class="rating">
                        <input type="radio" name="project[rating5]" id="stars-rating-5">
                        <label for="stars-rating-5"><i class="fa fa-star"></i></label>
                        <input type="radio" name="project[rating4]" id="stars-rating-4">
                        <label for="stars-rating-4"><i class="fa fa-star"></i></label>
                        <input type="radio" name="project[rating3]" id="stars-rating-3">
                        <label for="stars-rating-3"><i class="fa fa-star"></i></label>
                        <input type="radio" name="project[rating2]" id="stars-rating-2">
                        <label for="stars-rating-2"><i class="fa fa-star"></i></label>
                        <input type="radio" name="project[rating1]" id="stars-rating-1">
                        <label for="stars-rating-1"><i class="fa fa-star"></i></label>
                        <h4>* 난이도</h4>
                    </div>
                </section>

	            <div class="margin-bottom-40"></div>

                <!--Textarea-->
                <h4>* 프로젝트 설명</h4>
                <%= f.text_area :description, class: "form-control", rows: "20", maxlength: "65535" %>
                <!--End Textarea-->

                <div class="margin-bottom-40"></div>

                <footer style="text-align: right;">
                    <div class="ladda-btn">
                        <button type="submit" class="btn-u pull-right ladda-button" data-style="slide-down" style="border:0;font-weight:400;margin-left:5px;">Submit</button>
                    </div>

                    <button type="button" class="btn-u btn-u-default" onclick="window.history.back();">Back</button>
                </footer>

            <% end %>
        </div>
        
    </div>
</div>

<script>
	$('#sandbox-container input').datepicker({
		language: "ko",
		format: "yyyy-mm-dd",
	    autoclose: true,
	    todayHighlight: true,
	    todayBtn: "linked"
	});

	$('#sandbox-container2 input').datepicker({
		language: "ko",
		format: "yyyy-mm-dd",
	    autoclose: true,
	    todayHighlight: true,
	    todayBtn: "linked"
	});
</script>

app/views/projects/index.html.erb
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Projects</h1>
    </div>
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->
<% if @projects.present? %>
<div style="background: #f7f7f7;">
<div class="container content profile">
    <div class="row">
        <!-- Project Content -->            
        <div class="col-md-12">
            <div class="">

                <% @projects.each_slice(2) do |projects| %>
                <!--Projects-->
                <div class="row">
                    <% projects.each do |project| %>
                    <div class="col-sm-6" style="margin-bottom: 10px;"> 
                        <div class="projects">
                            <h2><a class="color-dark" href="<%= project_path(project) %>"><%= project.title %></a></h2>
                            <ul class="list-unstyled list-inline blog-info-v2">
                                <li>By: <a class="color-green" href="<%= user_profile_index_path(project.master.uid) %>"><%= project.master.nickname %></a></li>
                                <li><i class="fa fa-clock-o"></i> <%= project.start_date.strftime("%Y.%m.%d") %></li>
                            </ul>
                            <p style="height:80px;"><%= truncate(project.description, length: 150) %></p>
                            <br>

                            <% completeness =  ((Time.zone.now - project.start_date) / (project.end_date - project.start_date) * 100).to_i %>
                            <h3 class="heading-xs">Project Completeness <span class="pull-right"><%= completeness<0 ? 0 : completeness %>%</span></h3>
                            <div class="progress progress-u progress-xxs">
                                <div class="progress-bar progress-bar-u" role="progressbar" aria-valuenow="<%= completeness %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= completeness %>%">
                                </div>
                            </div>
                            <ul class="list-inline blog-info-v2">
                                <li>
                                    <strong><%= project.members.count %></strong>
                                    <span>Joined</span>
                                </li>
                                <li>
                                    <strong><%= completeness<0 ? 0 : completeness %>%</strong>
                                    <span>Completeness</span>
                                </li>
                                <li>
                                    <strong><%= ((project.end_date - Time.zone.now)/(60*60*24)).ceil %></strong>
                                    <span>days to go</span>
                                </li>
                            </ul>
                        </div>    
                        <div class="project-share">
                            <ul class="list-inline comment-list-v2 pull-left">
                                <li><i class="fa fa-eye"></i> <a><%= project.views %></a></li>
                                <!--<li><i class="fa fa-comments"></i> <a href="#">32</a></li>
                                <li><i class="fa fa-retweet"></i> <a href="#">77</a></li>-->
                            </ul>    
                            <ul class="list-inline star-vote pull-right">
                                <li style="font-size:14px;margin-right:10px;font-family:nanumbarunpenr;">난이도<li>
                                <% if project.rating5 %>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                <% elsif project.rating4 %>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star-o"></i></li>
                                <% elsif project.rating3 %>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star-o"></i></li>
                                    <li><i class="color-green fa fa-star-o"></i></li>
                                <% elsif project.rating2 %>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star-o"></i></li>
                                    <li><i class="color-green fa fa-star-o"></i></li>
                                    <li><i class="color-green fa fa-star-o"></i></li>
                                <% elsif project.rating1 %>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star-o"></i></li>
                                    <li><i class="color-green fa fa-star-o"></i></li>
                                    <li><i class="color-green fa fa-star-o"></i></li>
                                    <li><i class="color-green fa fa-star-o"></i></li>
                                <% end %>
                            </ul>
                        </div>
                    </div>

                    <% end %>
                </div><!--/end row-->
                <!--End Projects-->

                <hr>
                <% end %>
            </div>
        </div>
        <!-- End Project Content -->
    </div>
</div>
</div>
<% else %>
    <%= render 'noresults' %>
<% end %>

<!-- New Project Button -->
<a class="create-board" href="<%= new_project_path %>" style="z-index:1001;">
    <i class="icon-custom icon-lg rounded-x icon-bg-u glyphicon glyphicon-plus" style="line-height: 57px;font-size: 20px;" href="<%= new_notice_path %>"></i>
</a>
<!-- End New Project Button -->

app/views/projects/manage.html.erb
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Project Manage</h1>
    </div>
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<div class="container content">
    <div class="row">
    	<div class="col-md-3"></div>
    	<div class="col-md-6">

            <div class="headline"><h2>승인대기 관리</h2></div>

            <div class="margin-bottom-40"></div>

            <!--Table Striped-->
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>닉네임</th>
                        <th>성명</th>
                        <th>프로필 보기</th>
                        <th>승인</th>
                    </tr>
                </thead>
                <tbody>
                    <% @unreceiveds.each do |unreceived| %>
                        <tr>
                            <td><%= unreceived.uid %></td>
                            <td><%= unreceived.nickname %></td>
                            <td><%= unreceived.realname %></td>
                            <td><%= link_to '<i class="rounded-x fa fa-eye"></i>'.html_safe, user_profile_index_path(unreceived.uid) %></td>
                            <td><%= link_to '<i class="rounded-x fa fa-plus"></i>'.html_safe, approval_project_path(@project, user_id: unreceived.id) %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            <!--End Table Striped-->

            <div class="margin-bottom-40"></div>

            <div class="headline"><h2>멤버 관리</h2></div>

            <div class="margin-bottom-40"></div>

            <!--Table Striped-->
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>닉네임</th>
                        <th>성명</th>
                        <th>프로필 보기</th>
                        <th>강퇴</th>
                    </tr>
                </thead>
                <tbody>
                    <% @members.each do |member| %>
                        <tr>
                            <td><%= member.uid %></td>
                            <td><%= member.nickname %></td>
                            <td><%= member.realname %></td>
                            <td><%= link_to '<i class="rounded-x fa fa-eye"></i>'.html_safe, user_profile_index_path(member.uid) %></td>
                            <td><%= link_to '<i class="rounded-x fa fa-trash"></i>'.html_safe, leave_project_path(@project, user_id: member.id), method: :delete, data: { confirm: "정말 탈퇴시키겠습니까?" } unless @project.master.eql?(member) %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            <!--End Table Striped-->
        </div>
        <div class="col-md-3"></div>
	</div>
</div>

app/views/projects/show.html.erb
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Project Detail</h1>
    </div>
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<!--=== Content Part ===-->
<div class="container content"> 	
	<div class="row portfolio-item margin-bottom-50"> 

        <!-- Content Info -->        
        <div class="col-md-12">
        	<h2><%= @project.title %></h2>
            <p><%=h simple_format @project.description.html_safe %></p>
            <ul class="list-unstyled" style="margin-bottom:0px;">
            	<li><i class="fa fa-user color-green"></i> <%= @project.master.nickname %> / <%= @project.master.realname %></li>
            	<li><i class="fa fa-calendar color-green"></i> <%= @project.start_date.strftime("%Y.%m.%d") %> ~ <%= @project.end_date.strftime("%Y.%m.%d") %></li>
            	<!--<li><i class="fa fa-tags color-green"></i> Websites, Google, HTML5/CSS3</li>-->
            </ul>
            <ul class="list-inline star-vote" style="margin-left:0px;">
                <li style="font-size:14px;margin-right:10px;font-family:nanumbarunpenr;">난이도<li>
                <% if @project.rating5 %>
                    <li><i class="color-green fa fa-star"></i></li>
                    <li><i class="color-green fa fa-star"></i></li>
                    <li><i class="color-green fa fa-star"></i></li>
                    <li><i class="color-green fa fa-star"></i></li>
                    <li><i class="color-green fa fa-star"></i></li>
                <% elsif @project.rating4 %>
                    <li><i class="color-green fa fa-star"></i></li>
                    <li><i class="color-green fa fa-star"></i></li>
                    <li><i class="color-green fa fa-star"></i></li>
                    <li><i class="color-green fa fa-star"></i></li>
                    <li><i class="color-green fa fa-star-o"></i></li>
                <% elsif @project.rating3 %>
                    <li><i class="color-green fa fa-star"></i></li>
                    <li><i class="color-green fa fa-star"></i></li>
                    <li><i class="color-green fa fa-star"></i></li>
                    <li><i class="color-green fa fa-star-o"></i></li>
                    <li><i class="color-green fa fa-star-o"></i></li>
                <% elsif @project.rating2 %>
                    <li><i class="color-green fa fa-star"></i></li>
                    <li><i class="color-green fa fa-star"></i></li>
                    <li><i class="color-green fa fa-star-o"></i></li>
                    <li><i class="color-green fa fa-star-o"></i></li>
                    <li><i class="color-green fa fa-star-o"></i></li>
                <% elsif @project.rating1 %>
                    <li><i class="color-green fa fa-star"></i></li>
                    <li><i class="color-green fa fa-star-o"></i></li>
                    <li><i class="color-green fa fa-star-o"></i></li>
                    <li><i class="color-green fa fa-star-o"></i></li>
                    <li><i class="color-green fa fa-star-o"></i></li>
                <% end %>
            </ul>

            <% unless @project.joined?(current_user) %>
            <a href="<%= receive_project_path(@project) %>" class="btn-u btn-u-large">JOIN THE PROJECT</a>
            <% else %>
                <% if @project.unreceived.include?(current_user) %>
                    <br><h4>상태: 프로젝트 가입 승인대기 중입니다.</h4>
                <% else %>
                    <br><h4>상태: 프로젝트 멤버입니다.</h4>
                <% end %>
            <% end %>

            <% if current_user == @project.master %>
            <a href="<%= manage_project_path(@project) %>" class="btn-u btn-u-large btn-u-blue">MANAGE MEMBERS</a>
            <a href="<%= edit_project_path(@project) %>" class="btn-u btn-u-large btn-u-default">EDIT</a>
            <%= link_to "Delete", project_path(@project), data: { confirm: "Are you sure?" }, class: "btn-u btn-u-large btn-u-red" ,method: :delete %>
            <% end %>
        </div>
        <!-- End Content Info -->        
    </div><!--/row-->

    <div class="tag-box tag-box-v2">
        <p>"두 마리 토끼를 잡으려다 둘 다 놓친다" 라는 속담이 있듯이, 너무 많은 프로젝트에 참여는 오히려 제대로된 학습이 안될 수도 있습니다.</p>
    </div>

    <div class="margin-bottom-20 clearfix"></div>    

    <!-- Recent Works -->
    <div class="owl-carousel-v1 owl-work-v1 margin-bottom-40">
        <div class="headline"><h2 class="pull-left">Members</h2>
            <div class="owl-navigation">
                <div class="customNavigation">
                    <a class="owl-btn" style="visibility:hidden;"></a>
                    <a class="owl-btn" style="visibility:hidden;"></a>
                </div>
            </div><!--/navigation-->
        </div>

        <% @project.members.each_slice(6) do |members| %>
        <div class="row team-v6 margin-bottom-60">
            <% members.each do |member| %>
            <div class="col-md-2 col-sm-6 md-margin-bottom-50">
                <%= image_tag member.avatar.url, class: "img-responsive", style: "height:166px; width:166px;" %>
                <span><%= member.nickname %></span>
                <small><%= user_roles(member) %></small>
            </div>
            <% end %>
        </div><!--/end team v6-->

        <% end %>

    </div>    
    <!-- End Recent Works -->
</div><!--/container-->	 	
<!--=== End Content Part ===-->