config/routes.rb
Rails.application.routes.draw do

  # GENERAL ROUTES
  root 'board_line#index'

  devise_for :users
  resources :users, only: [:show, :update] do
    member do
      patch 'update_avatar'
      put 'update_avatar'
      post 'like'
      delete 'unlike'
    end

    resources :profile, only: [:index]
    # 프로필 정보 수정 (닉네임, 한줄소개)
    put   '/profile' => 'profile#update'
    patch '/profile' => 'profile#update'
    # Social 정보 수정
    post  '/social'  => 'profile#social'
  end
  # S Finger login
  get '/sfinger' => 'users#sfinger'
  post '/sfinger' => 'users#sfinger_register'

  # 게시판 형태
  resources :boards, only: [] do
    resources :comments, only: [:create, :edit, :destroy, :update]
  end
  resources :notices, controller: 'board_notice'
  resources :frees, controller: 'board_free'
  resources :reviews, controller: 'board_review'
  resources :genealogies, controller: 'board_genealogy'
  resources :galleries, controller: 'board_gallery'
  resources :presentations, controller: 'board_presentation'
  resources :documents, controller: 'board_document'
  resources :blogs, controller: 'board_blog'
  resources :lines, controller: 'board_line', only: [:index, :create, :destroy]
  resources :grades, controller: 'board_grade', except: [:index]
  resources :reports, controller: 'board_report'

  # 캘린더
  resources :calendar, except: :new

  # Project
  resources :projects do
    member do
      get 'manage'
      get 'receive'
      get 'approval'
      delete 'leave'
    end
  end

  # 문의
  resources :inquiries, only: [:show, :create, :destroy]

  # Static Pages
  get '/privacy_policy' => 'base#privacy'
  get '/terms_service' => 'base#terms'
  get '/contact' => 'base#contact'
  get '/members' => 'users#index'


  # ADMIN ROUTES
  get '/admin/membership'
  patch '/admin/membership' => 'admin#membership_update'
  put '/admin/membership' => 'admin#membership_update'
  get '/admin/grades'
  patch '/admin/grades' => 'admin#grades_update'
  put '/admin/grades' => 'admin#grades_update'
  get '/admin/inquiries'
  
  # API ROUTES
  namespace :api, path: '/', constraints: { subdomain: 'api' } do
    namespace :v1 do
      get '/authenticate' => 'auth#get_token'
      resources :notices, controller: 'board_notice'
    end
  end

  # , constraints: { subdomain: 'api' }

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/board_report_controller.rb
class BoardReportController < BoardsController
	def index
		super
		@page   	= params[:page].to_i == 0 ? 1 : params[:page].to_i
		@type   	= BoardType.where(name: "reports").first
		@boards  	= @type.boards
		@page_max	= @boards.present? ? (@boards.count-1) / 10 + 1 : 1
		@boards 	= @boards.paginate(:page => params[:page], :per_page => 10)
	end

	def show
		super
	end

	def new
		super
		@board_type	= BoardType.where(name: "reports").first
		@board 		= @board_type.boards.new
		@labels		= Label.all[0..2]
	end

	def create
		super
		@board.board_type = BoardType.where(name: "reports").first
		@board.label      = Label.where(id: params[:board][:label_id]).first
		@board.save
		@board.comments.create(
			user: Role.where(name: "admin").first.users.first,
			contents: "제보에 감사드립니다. 빠른 시일 내에 확인하여 수정하도록 하겠습니다."
		)

		redirect_to report_path(@board)
	end

	def destroy
		super
	end

	def edit
		super
		if current_user.has_role?(:admin)
			@labels	= Label.all
		else
			@labels = Label.all[0..2]
		end
	end

	def update
		super
		@board.label      = Label.where(id: params[:board][:label_id]).first
		@board.isopen	  = params[:board][:isopen].eql?("true")
		@board.save
	end
end

app/helpers/board_report_helper.rb
module BoardReportHelper
end

app/views/board_report/edit.html.erb
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Edit Board</h1>
    </div>
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<div class="bg-color-light">
    <div class="container content-sm">
        <div class="tag-box tag-box-v3 form-page">
            <div class="headline"><h3><%= @board_type.realname %></h3></div>                
            <%= form_for @board, url: url_for(controller: controller.controller_name, action: 'update') do |f| %>
                <!--Inputs-->
                <h4>Title</h4>
                <div id="board-title" class=""> 
                    <%= f.text_field :title , class: "form-control", maxlength: "75" %>
                </div>
                <!--End Inputs-->

                <div class="margin-bottom-40"></div>

                <h4>Label</h4>
                <h5 style="color:#c7254e;">Bug(기능오류), Security(보안관련), Enhancement(기능추가, 개선, 건의)</h5>
                <div class="col-lg-4" style="padding-left:0px;"> 
                    <%= f.select :label_id , options_from_collection_for_select(@labels, "id", "name", @board.label.id), {}, class: "form-control" %>
                </div>

                <div class="margin-bottom-40"></div>

                <% if current_user.has_role?(:admin) %>
                <h4>Status</h4>
                <div class="col-lg-4" style="padding-left:0px;"> 
                    <% if @board.isopen %>
                    <%= f.select :isopen, '<option value="true" selected="selected">Open</option><option value="false">Closed</option>'.html_safe ,{}, class: "form-control" %>
                    <% else %>
                    <%= f.select :isopen, '<option value="true">Open</option><option value="false" selected="selected">Closed</option>'.html_safe ,{}, class: "form-control" %>
                    <% end %>
                </div>

                <div class="margin-bottom-40"></div>
                <% end %>

                <!--Textarea-->
                <h4 id="content_head">Contents</h4>
                <div id="summernote" class=""></div>
                <%= f.hidden_field :contents, maxlength: "65535" %>
                <!--End Textarea-->

                <div class="margin-bottom-40"></div>

                <footer style="text-align: right;">
                    <div class="ladda-btn">
                        <button type="submit" class="btn-u pull-right ladda-button" data-style="slide-down" onclick="summernote_submit()" style="border:0;font-weight:400;margin-left:5px;">Submit</button>
                    </div>

                    <button type="button" class="btn-u btn-u-default" onclick="window.history.back();">Back</button>
                </footer>

            <% end %>
        </div>
        
    </div>
</div>
<script type="text/javascript">
    $('#summernote').summernote({
        height: 500
    });
    $('#summernote').code('<%= @board.contents.gsub(/^\s+|\n|\s+$/, "").html_safe %>');

</script>

app/views/board_report/index.html.erb
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left"><%= @type.realname %></h1>
    </div>
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<!--=== Search Block Version 2 ===-->
<div class="search-block">
    <div class="container">
        <div class="col-md-6 col-md-offset-3">
            <h2>Thanks for your report</h2>
            <div style="text-align:center;">
                <p>버그 리포트 게시판은 아래의 3가지 주제에 관해 제보를 받고 있습니다.</p>
                <p>Bug(기능오류), Security(보안관련), Enhancement(기능추가, 개선, 건의)</p><br />
                <%= link_to "제보하기", new_report_path, class: "btn-u" %>
            </div>
        </div>
    </div>
</div><!--/container-->
<!--=== End Search Block Version 2 ===-->

<div class="container content-sm">
    <!-- Begin Table Search v2 -->
    <div class="table-search-v2 margin-bottom-30">
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>User Name</th>
                        <th>About</th>
                        <th>Labels</th>
                        <th>Status</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                    <% @boards.each do |board| %>
                    <tr>
                        <td>
                            <div class="user-names">
                                <span><%= board.user.nickname %></span>
                                <small>(<%= board.user.realname %>)</small>
                            </div>
                        </td>
                        <td class="td-width">
                            <h3><a href="<%= report_path(board) %>"><%= truncate board.title, length: 36 %></a></h3>
                            <small class="hex"><%= board.likes.count %> recommend</small>
                        </td>
                        <td>
                            <% case board.label.name %>
                            <% when "Security" %>
                            <span class="label label-danger">Security</span>
                            <% when "Bug" %>
                            <span class="label label-warning">Bug</span>
                            <% when "Enhancement" %>
                            <span class="label label-info">Enhancement</span>
                            <% when "Duplicate" %>
                            <span class="label label-light">Duplicate</span>
                            <% when "Invalid" %>
                            <span class="label label-default">Invalid</span>
                            <% end %>
                        </td>
                        <td>
                            <% if board.isopen %>
                            <span class="label label-light">Open</span>
                            <% else %>
                            <span class="label label-dark">Closed</span>
                            <% end %>
                        </td>
                        <td style="text-align:center;">
                            <p><%= board.created_at.strftime("%Y. %m. %d") %></p>
                        </td>
                    </tr>
                    <% end %>             
                </tbody>
            </table>
        </div>
    </div>
    <!-- End Table Search v2 -->

    <!-- Pager v3 -->
    <ul class="pager pager-v3 pager-md no-margin-bottom">
        <li class="previous">
            <%= link_to "&larr; Older".html_safe, { controller: controller.controller_name, action: "index", page: @page-1 } if @page > 1 %>
        </li>
        <li class="page-amount"><%= "#{@page} of #{@page_max}" %></li>
        <li class="next">
            <%= link_to "Newer &rarr;".html_safe, { controller: controller.controller_name, action: "index", page: @page+1 } if @page < @page_max %>
        </li>
    </ul>
    <!-- End Pager v3 -->
</div>

app/views/board_report/new.html.erb
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">New Board</h1>
    </div>
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<div class="bg-color-light">
    <div class="container content-sm">
        <div class="tag-box tag-box-v3 form-page">
            <div class="headline"><h3><%= @board_type.realname %></h3></div>                
            <%= form_for @board, url: url_for(controller: controller.controller_name, action: 'create') do |f| %>
                <!--Inputs-->
                <h4>Title</h4>
                <div id="board-title" class=""> 
                    <%= f.text_field :title , class: "form-control", maxlength: "75" %>
                </div>
                <!--End Inputs-->

                <div class="margin-bottom-40"></div>

                <h4>Label</h4>
                <h5 style="color:#c7254e;">Bug(기능오류), Security(보안관련), Enhancement(기능추가, 개선, 건의)</h5>
                <div class="col-lg-4" style="padding-left:0px;"> 
                    <%= f.select :label_id , options_for_select(@labels.map{|s| [s.name, s.id]}), {}, class: "form-control" %>
                </div>

                <div class="margin-bottom-40"></div>

                <!--Textarea-->
                <h4 id="content_head">Contents</h4>
                <div id="summernote" class=""></div>
                <%= f.hidden_field :contents, maxlength: "65535" %>
                <!--End Textarea-->

                <div class="margin-bottom-40"></div>

                <footer style="text-align: right;">
                    <div class="ladda-btn">
                        <button type="submit" class="btn-u pull-right ladda-button" data-style="slide-down" onclick="summernote_submit()" style="border:0;font-weight:400;margin-left:5px;">Submit</button>
                    </div>

                    <button type="button" class="btn-u btn-u-default" onclick="window.history.back();">Back</button>
                </footer>

            <% end %>
        </div>
        
    </div>
</div>
<script type="text/javascript">
    $('#summernote').summernote({
        height: 500
    });
</script>